name: HypeLobby
author: QuadrixYT
version: 1.0
api-version: 1.16
depend:
  - CloudNet-Bridge
main: eu.hypetime.spigot.hypelobby.HypeLobby

commands:
  build:
    description: Build Command
  set:
    description: Set Location Command
  top5:
    description: GunBattle top5
  stats:
    description: GunBattle Stats
  sit:
    description: sit command
  patchnodes:
    description: Patchnodes command